# Generated by Django 4.2.11 on 2025-09-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EnergyIndicator",
            fields=[
                (
                    "indicator_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(max_length=20)),
            ],
            options={
                "ordering": ["indicator_id"],
            },
        ),
        migrations.CreateModel(
            name="EnergyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("value", models.FloatField()),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("fifteen_minutes", "15 minutes"),
                            ("hour", "hourly"),
                            ("day", "daily"),
                            ("month", "monthly"),
                            ("year", "yearly"),
                        ],
                        default="hour",
                        max_length=20,
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_points",
                        to="energy_analysis.energyindicator",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["indicator", "timestamp"],
                        name="energy_anal_indicat_8e79a3_idx",
                    )
                ],
                "unique_together": {("indicator", "timestamp", "resolution")},
            },
        ),
    ]
