# Generated by Django 4.2.11 on 2025-08-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyEnergySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("renewable_generation_mwh", models.FloatField()),
                ("total_demand_mwh", models.FloatField()),
                ("renewable_surplus_mwh", models.FloatField()),
                ("renewable_percentage", models.FloatField()),
                (
                    "avg_price_eur_mwh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EnergyIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("esios_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=500)),
                ("short_name", models.CharField(blank=True, max_length=200)),
                ("unit", models.CharField(default="MWh", max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("generation", "Generation"),
                            ("demand", "Demand"),
                            ("price", "Price"),
                            ("percentage", "Percentage"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "technology",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("solar_pv", "Solar Photovoltaic"),
                            ("solar_thermal", "Solar Thermal"),
                            ("wind_onshore", "Wind Onshore"),
                            ("wind_offshore", "Wind Offshore"),
                            ("hydro_large", "Hydro Large"),
                            ("hydro_small", "Hydro Small"),
                            ("nuclear", "Nuclear"),
                            ("biomass", "Biomass"),
                            ("biogas", "Biogas"),
                            ("renewable_waste", "Renewable Waste"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("is_renewable", models.BooleanField(default=False)),
                ("is_variable_renewable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["esios_id"],
            },
        ),
        migrations.CreateModel(
            name="EnergyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("value", models.FloatField()),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("5min", "5 Minutes"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_source", models.CharField(default="esios", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_points",
                        to="energy_analysis.energyindicator",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
                "indexes": [
                    models.Index(
                        fields=["timestamp", "indicator"],
                        name="energy_anal_timesta_61d1a7_idx",
                    ),
                    models.Index(
                        fields=["indicator", "timestamp"],
                        name="energy_anal_indicat_8e79a3_idx",
                    ),
                    models.Index(
                        fields=["timestamp", "granularity"],
                        name="energy_anal_timesta_4884d9_idx",
                    ),
                ],
                "unique_together": {("indicator", "timestamp")},
            },
        ),
    ]
