# Generated by Django 4.2.11 on 2025-09-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEnergySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('data_source', models.CharField(choices=[('database', 'Local Database'), ('esios', 'ESIOS API')], max_length=20)),
                ('peak_vre_penetration', models.FloatField()),
                ('peak_vre_hour', models.TimeField()),
                ('sustained_high_vre_hours', models.IntegerField()),
                ('max_netload_ramp_gw', models.FloatField()),
                ('ramp_window_start', models.TimeField()),
                ('ramp_window_end', models.TimeField()),
                ('load_balancing_gap_hours', models.IntegerField()),
                ('peak_demand_hour', models.TimeField()),
                ('shiftable_energy_gwh', models.FloatField()),
                ('flexibility_window_start', models.TimeField(null=True)),
                ('flexibility_window_end', models.TimeField(null=True)),
                ('hourly_data_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Energy Summary',
                'verbose_name_plural': 'Daily Energy Summaries',
                'ordering': ['-date'],
            },
        ),
    ]
