# Generated by Django 4.2.11 on 2025-08-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("energy_analysis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="energydata",
            name="energy_anal_timesta_4884d9_idx",
        ),
        migrations.AlterUniqueTogether(
            name="energydata",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="energydata",
            name="agg_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="energydata",
            name="geo_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="energydata",
            name="geo_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="energydata",
            unique_together={("indicator", "timestamp", "geo_id")},
        ),
        migrations.AddIndex(
            model_name="energydata",
            index=models.Index(fields=["geo_id"], name="energy_anal_geo_id_8092da_idx"),
        ),
        migrations.RemoveField(
            model_name="energydata",
            name="granularity",
        ),
    ]
