# Generated by Django 4.2.11 on 2025-09-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_analysis', '0002_dailyenergysummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyenergysummary',
            name='total_hours',
            field=models.IntegerField(default=24),
        ),
    ]
