# Generated by Django 4.2.11 on 2025-08-31 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "energy_analysis",
            "0002_remove_energydata_energy_anal_timesta_4884d9_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="energydata",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="energydata",
            name="resolution",
            field=models.CharField(
                choices=[("5min", "5 minute"), ("hour", "Hourly")],
                default="hour",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="energydata",
            unique_together={("indicator", "timestamp", "geo_id", "resolution")},
        ),
        migrations.RemoveField(
            model_name="energydata",
            name="agg_value",
        ),
    ]
