# Generated by Django 4.2.11 on 2026-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_analysis', '0003_dailyenergysummary_total_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCurtailmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('data_source', models.CharField(choices=[('database', 'Local Database'), ('esios', 'ESIOS API')], max_length=20)),
                ('total_curtailed_mwh', models.FloatField()),
                ('estimated_revenue_lost_eur', models.FloatField()),
                ('peak_curtailment_pct', models.FloatField()),
                ('peak_curtailment_hour', models.TimeField()),
                ('transmission_constrained_hours', models.IntegerField(blank=True, null=True)),
                ('distribution_constrained_hours', models.IntegerField(blank=True, null=True)),
                ('hourly_data_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Curtailment Summary',
                'verbose_name_plural': 'Daily Curtailment Summaries',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyCurtailmentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_curtailed_mwh', models.FloatField()),
                ('total_revenue_lost_eur', models.FloatField()),
                ('avg_daily_curtailed_mwh', models.FloatField()),
                ('days_with_curtailment', models.IntegerField()),
                ('worst_day', models.DateField()),
                ('worst_day_mwh', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Monthly Curtailment Summary',
                'verbose_name_plural': 'Monthly Curtailment Summaries',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
