# Generated by Django 4.2.11 on 2026-02-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_analysis', '0004_dailycurtailmentsummary_monthlycurtailmentsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailycurtailmentsummary',
            name='distribution_constrained_hours',
        ),
        migrations.RemoveField(
            model_name='dailycurtailmentsummary',
            name='peak_curtailment_pct',
        ),
        migrations.RemoveField(
            model_name='dailycurtailmentsummary',
            name='transmission_constrained_hours',
        ),
        migrations.AddField(
            model_name='dailycurtailmentsummary',
            name='distribution_curtailment_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailycurtailmentsummary',
            name='peak_curtailment_mwh',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailycurtailmentsummary',
            name='transmission_curtailment_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlycurtailmentsummary',
            name='distribution_curtailment_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlycurtailmentsummary',
            name='total_curtailment_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlycurtailmentsummary',
            name='transmission_curtailment_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
