# Generated by Django 4.2.11 on 2026-03-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_analysis', '0005_remove_dailycurtailmentsummary_distribution_constrained_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycurtailmentsummary',
            name='data_source',
            field=models.CharField(choices=[('database', 'Local Database'), ('esios', 'ESIOS API'), ('caiso', 'CAISO'), ('spp', 'SPP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailycurtailmentsummary',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailyenergysummary',
            name='data_source',
            field=models.CharField(choices=[('database', 'Local Database'), ('esios', 'ESIOS API'), ('caiso', 'CAISO'), {'SPP', 'spp'}], max_length=20),
        ),
        migrations.AlterField(
            model_name='dailyenergysummary',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailycurtailmentsummary',
            unique_together={('date', 'data_source')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyenergysummary',
            unique_together={('date', 'data_source')},
        ),
    ]
