# Generated by Django 4.2.11 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_analysis', '0006_alter_dailycurtailmentsummary_data_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='Stable frontend key, e.g. hero_title or bess_explainer_text.', max_length=120, unique=True)),
                ('value', models.TextField()),
                ('page', models.CharField(blank=True, db_index=True, help_text='Optional page grouping for easier filtering in admin.', max_length=80)),
                ('section', models.CharField(blank=True, db_index=True, help_text='Optional section grouping for easier filtering in admin.', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Copy',
                'verbose_name_plural': 'Site Copy',
                'ordering': ['page', 'section', 'key'],
            },
        ),
    ]
