# Generated by Django 5.1.4 on 2025-02-18 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("client", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FILM", "Film Only"),
                            ("PHOTO", "Photo Only"),
                            ("BOTH", "Film and Photo"),
                        ],
                        default="FILM",
                        max_length=5,
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                ("web_url", models.URLField(blank=True, null=True)),
                ("date", models.DateField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Photographer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("instagram", models.CharField(blank=True, max_length=30, null=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PhotoShoot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("show", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photo_shoots",
                        to="portfolio_app.campaign",
                    ),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photo_shoots",
                        to="portfolio_app.photographer",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="photos/")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "is_portrait",
                    models.BooleanField(
                        default=False,
                        help_text="Check if photo is in portrait orientation",
                    ),
                ),
                ("photo_shoot_order", models.PositiveIntegerField(default=0)),
                (
                    "carousel_order",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional. Only set for photos that should appear in the homepage carousel",
                        null=True,
                    ),
                ),
                ("show", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="portfolio_app.photographer",
                    ),
                ),
                (
                    "photo_shoot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="portfolio_app.photoshoot",
                    ),
                ),
            ],
            options={
                "ordering": ["photo_shoot_order"],
                "indexes": [
                    models.Index(
                        fields=["carousel_order"], name="portfolio_a_carouse_473fdd_idx"
                    ),
                    models.Index(
                        fields=["photo_shoot_order"],
                        name="portfolio_a_photo_s_17513d_idx",
                    ),
                ],
            },
        ),
    ]
